### ISSUE TITLE
7.0以上UI有些小问题

### ISSUE THREAD

**Issue by WencaiHwcazy** [twiceyuan/DropdownMenu#2]
东西还不错，好用，不过在7.0版本以上，某些手机，比如华为，小米，此控件用在frament中，第二个frament中会出现展开后，选项消失的情况
if (Build.VERSION.SDK_INT >= 24) {
            ViewTreeObserver vto = getViewTreeObserver();
            vto.addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
                @Override
                public void onGlobalLayout() {
                    getViewTreeObserver().removeOnGlobalLayoutListener(this);
                    int[] location = new int[2];
                    getLocationOnScreen(location);
                    int x = location[0];
                    final int y = location[1];
                    mPopupWindow.setHeight(screenHeight - y - getHeight());
                }
            });
        }
getHeight() 在第二个frament中初始化后取不到值
getHeight()等于0

**Comment by twiceyuan** [comment]
能否提供一个能够复现的最小集成项目

**Comment by twiceyuan** [comment]
可测试一下 1.1.7 版本是否修复，感谢反馈
